baseURL = "https://richdmart.in"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en"
theme = "hugo-devresume-theme"
title = "Richard Martin"
[params]
author = "Richard Martin"
description = "International Business Student & Casual Developer"
primaryColor = "#c0392b"
textPrimaryColor = "#292929"
[params.awards]
enable = false
[[params.awards.list]]
body = "Microsoft lorem ipsum"
date = "2019"
name = "Award Lorem Ipsum"
[[params.awards.list]]
body = "Oracle Aenean"
date = "2017"
name = "Award Donec Sodales"
[params.contact]
enable = true
location = "Knoxville, Tennessee"
[[params.contact.list]]
icon = "fas fa-phone-square"
text = "(865) 274-9603"
url = "tel:#"
[[params.contact.list]]
icon = "fas fa-envelope-square"
text = "inbox@richdmart.in"
url = "mailto:#"
[[params.contact.list]]
icon = "fas fa-globe"
text = "www.richdmart.in"
url = "#"
[[params.contact.list]]
icon = "fas fa-globe"
text = "www.dropbyte.ch"
url = "https://dropbyte.ch"
[params.education]
enable = true
[[params.education.list]]
dates = "2018-2021"
degree = "Major in International Business"
university = "Maryville College"
[[params.education.list]]
dates = "2016-2018"
degree = "Major in Computer Science"
university = "East Tennessee State University"
[params.experience]
enable = true
[[params.experience.list]]
company = "Anderson Busby PLLC"
dates = "Mar 2020 - Present"
details = "Delivered and drafted legal documents"
title = "Law Runner"
[[params.experience.list.items]]
details = "Clerical work, including filing and organizing"
[[params.experience.list.items]]
details = "Delivery of legal documents to Courts, other firms, and clients"
[[params.experience.list.items]]
details = "Drafting and organization of legal documents"
[[params.experience.list]]
company = "Calhoun's Restaurant"
dates = "May 2019 - Nov 2019"
details = "Ensured a satisfactory dining experience for guests"
title = "Server"
[[params.experience.list]]
company = "Metz Culinary Management"
dates = "Sept 2018 - May 2019"
details = "Organized and implemented a marketing program for on-campus dining"
title = "Marketing Intern"
[[params.experience.list]]
company = "Neighborhood Nerds"
dates = "Jun 2017 - Aug 2018"
details = "Developed documentation and business infrastructure for day-to-day operations"
title = "Assistant Manager"
[[params.experience.list]]
company = "Neighborhood Nerds"
dates = "May 2017 - Jun 2018"
details = "Worked with members to provide reliable tech support and form customer relationships"
title = "IT Support Technician"
[[params.experience.list]]
company = "Structured Solutions"
dates = "Jan 2017 - Jan 2018"
details = "Installed network wiring in residential areas and configured large networks"
title = "Network Technician"
[[params.experience.list]]
company = "Dean's Restaurant & Bakery"
dates = "Feb 2016 - Aug 2016"
details = "Provided quality service consistent with a small, local diner experience"
title = "Server"
[params.information]
enable = true
[[params.information.list]]
title = "Papers"
[[params.information.list.items]]
details = "2020 · Multinational Corporations in Global Politics: Influence and Development"
[[params.information.list.items]]
details = "2020 · Appalachia Behind the Fence"
[[params.information.list.items]]
details = "2019 · Interfaith Dialogue and Religious Tensions"
[[params.information.list.items]]
details = "2019 · Life in the First Global Civilization"
[[params.information.list.items]]
details = "2019 · Truth and Reconciliation in the United States"
[params.interests]
enable = true
[[params.interests.list]]
name = "Running"
[[params.interests.list]]
name = "Guitar"
[[params.interests.list]]
name = "Coding"
[[params.interests.list]]
name = "Video Games"
[[params.interests.list]]
name = "Fishing"
[params.languages]
enable = true
[[params.languages.list]]
level = "Native"
name = "English"
[[params.languages.list]]
level = "Conversational"
name = "German"
[params.profile]
avatar = "static/assets/images/avatar.png"
enable = true
name = "Richard Martin"
tagline = "International Business Student & Founder of DropByte Remote Tech Support"
[params.projects]
enable = true
[[params.projects.list]]
meta = "Remote Tech Support"
tagline = "DropByte is a tech support company which operates over Zoom video chat to provide quick and accessible service to clients. Additionally, DropByte develops proprietary tech guides aimed at teaching clients how to use their technology so that they can better utilize their devices."
title = "DropByte"
[params.skills]
enable = true
[[params.skills.list]]
title = "Technical"
[[params.skills.list.items]]
details = "JavaScript/React, HTML & CSS"
[[params.skills.list.items]]
details = "Python & Java"
[[params.skills.list.items]]
details = "Microsoft Office, Adobe Creative Cloud"
[[params.skills.list.items]]
[[params.skills.list]]
title = "Professional"
[[params.skills.list.items]]
details = "Effective communicator"
[[params.skills.list.items]]
details = "Team player"
[[params.skills.list.items]]
details = "Strong problem solver"
[[params.skills.list.items]]
details = "Hard worker"
[params.social]
enable = true
[[params.social.list]]
icon = "fab fa-github-square"
title = "richdmartin"
url = "//github.com/richdmartin"
[[params.social.list]]
icon = "fab fa-linkedin"
title = "richdmartin"
url = "//linkedin.com/in/richdmartin"
[[params.social.list]]
icon = "fab fa-twitter-square"
title = "@richdmartin"
url = "//twitter.com/richdmartin"
[params.summary]
enable = true
text = "I am an international business student at Maryville College, and I work part-time at Anderson Busby PLLC, a law firm based in Knoxville. I am also working on a side project, DropByte, which is a remote tech support company aimed at teaching people how to use their tech, all while addressing their technical problems. In my free time, I enjoy running, coding, playing guitar, and playing video games."
